### ISSUE TITLE
How to generate my own training data?

### ISSUE THREAD

**Issue by minolta001** [devinluo27/potential-motion-plan-release#2]
Hello. Nice work!

May I know how you generate training data for Maze2D?

**Comment by devinluo27** [comment]
Hello,

Thank you for your interest.

This [folder](https://github.com/devinluo27/potential-motion-plan-release/tree/1bb3c037c3173a7fa9bc76cd05e09fc660c3c99f/pb_diff_envs/pb_diff_envs/scripts)  contains scripts to generate training data. 

At a high level, the dataset is a random walk in the environment -- we randomly sample a goal in the environment and use BIT* to generate a path from the current state to the goal state. This sampling procedure is repeated until the dataset reaches the specified length.

You can use this [script](https://github.com/devinluo27/potential-motion-plan-release/blob/1bb3c037c3173a7fa9bc76cd05e09fc660c3c99f/pb_diff_envs/pb_diff_envs/scripts/gen_m2d_mp.sh) for Maze2D. Note that this script utilizes CPU multiprocessing to increase speed, and you can set this `num_cores` according to your machine's configuration.

**Comment by minolta001** [comment]
Thanks for your response! This is very helpful. 

May I ask you one extra question if you don't mind?

I can see your work also works with KUKA arm. In the code implementation, the outputs of your model are just the pose of end-effector and there is another lower-level controller to solve the joint control given end effector poses, or your work can train a forward kinematics model to solve joint space control?

**Comment by devinluo27** [comment]
For KUKA arm, our model's output is already a trajectory of the robot joint state (of shape [horizon, 7]), so I believe that lower-level controllers can be directly applied.

**Comment by minolta001** [comment]
Thank you! I guess then I should go through the KUKA code to see what's going on. 

Again, thanks for your time!

**Comment by basusattwik** [comment]
Hello. I am wondering if this diffusion based planner would with a different dataset such as one containing apartment floorplans? Link: https://github.com/TeaganLi/HouseExpo

What kind of changes would be needed? Thanks.

**Comment by devinluo27** [comment]
Hi Sattwik. 

To work on different datasets, I guess you might need to find a good representation for the layout of each environment such that the motion planner can efficiently learn and generalize to unseen environments (in our setting, we use the coordinates of the obstacles in the environment). 

In this floorplan dataset, one potential way is to directly try using the floorplan image as the representation, given that the number of floorplans in the dataset is large (e.g., encoding the image to latent and use that latent to condition the denoiser network). Or you can also design some other representation according to the structure of the environments. 

Let me know if you have further questions.
