### ISSUE TITLE
No such file or directory: 'logs/randSmaze2d-ng3ks25k-ms55nw6-hExt05-v0/diffusion/rSmaze_nw6_hExt05_exp_H48_T100/model_config.txt'

### ISSUE THREAD

**Issue by Andrii0607** [devinluo27/potential-motion-plan-release#3]
After downloading pre-trained models, when I run planning for Maze2D environment,
this error occurrs.
  File "/home/ubuntu/potential-motion-plan-release/./diffuser/utils/config.py", line 77, in __call__
    with open(m_path, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'logs/randSmaze2d-ng3ks25k-ms55nw6-hExt05-v0/diffusion/rSmaze_nw6_hExt05_exp_H48_T100/model_config.txt'

Where I can find model_config.txt file?

**Comment by devinluo27** [comment]
Hi,

Can you check if this relative path `logs/randSmaze2d-ng3ks25k-ms55nw6-hExt05-v0/diffusion/rSmaze_nw6_hExt05_exp_H48_T100/` exists? In which folder did you launch the planning? You might want to launch the planning from `potential-motion-plan-release/`.

As in Line 77, the code is just writing the model architecture to `model_config.txt`, so you don't need to find the `model_config.txt`.

**Comment by Andrii0607** [comment]
Hi devinluo27,

Thank you for your quick response. It turned out that I placed a wrong file.
Now the program works perfectly.
